TypeText WindowsKey, "r" -- Typetext command for windows shortcuts
Typetext "chrome" -- To enter string on SUT
Typetext returnKey -- Typetext command for keyword
click imageName:"AddressBar",waitFor:10
typetext controlKey,l
Typetext "demoblaze.com",return -- String with keyword
Typetext windowsKey,upArrow  --- Maxmize the browser window

log "something"
wait 0.02 milliseconds
log "something"
wait 1 minute
log "something"










